language: crystal
  - crystal spec
  - crystal tool format --check
  - crystal docs

  deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    project_name: horrendo/pg_sql_lexer
    on:
      branch: master
    local_dir: docs